version: '3.7'

services:
  nginx-mtls:
    build: .
    image: nginx:mtls
    container_name: nginx-mtls
    environment:
      - SERVER_CERT
      - SERVER_KEY
      - CLIENT_CA
      - PROXY_URL
      - PROXY_PORT
      - RESOLVER
      - ECS_CONTAINER_METADATA_URI_V4
    restart: unless-stopped
    ports:
    - "8443:8443"
    - "8080:8080"
